### ISSUE TITLE
page parameter/message is silently ignored

### ISSUE THREAD

**Issue by grexe** [HaikuArchives/BePDF#116]
The application usage help says thus:

> `Usage: /boot/system/apps/BePDF/BePDF [options] [<PDF-file> [<page>]]`

The source even contains a definition of a page num message in https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/BepdfApplication.cpp#L63 and it is used when parsing arguments in
https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/BepdfApplication.cpp#L664
and added to the refs received message in
https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/BepdfApplication.cpp#L676
but in the actual `RefsReceived` method it is silently ignored, making the parameter useless:
https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/BepdfApplication.cpp#L531

This would really be important for scripting, I took a look but the application does not separate between UI and backend code, making this fix harder than necessary...

You can easily test the message handling part via
> `hey BePDF '_RRC' with "bepdf:page_num"=11`

or use the application signature `application/x-vnd.mp-xpdf` to go sure.

**Comment by grexe** [comment]
please reopen and use latest PR as this is a much cleaner solution, reusing existing flow when coming from pagenum TextView, but extends on that. Also fixes a display issue with the page listview not updating selection properly when jumping to the page via arguments.

**Comment by humdingerb** [comment]
Very good!
