### ISSUE TITLE
Switch to using vector icons

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/BePDF#15]
Mockup: ![bepdf-mockup](https://f.cloud.github.com/assets/3889965/1699723/21803fbe-5fbc-11e3-9863-95f96dbc200b.png)

**Comment by diversys** [comment]
Now that BePDF uses BToolbar it should be possible now. GCI task?

**Comment by waddlesplash** [comment]
Done in fd605d06e8d2888d687838de7f2829af077b3553 and 92e016c8fd36687d29b0cc010241233dff1542ae.
