### ISSUE TITLE
HaikuDepot has a fatal error when installing BePDF, yet BePDF is successfully installed.

### ISSUE THREAD

**Issue by jfjhh** [HaikuArchives/BePDF#19]
HaikuDepot has a fatal error when installing BePDF, yet BePDF is successfully installed.

![haikudepotfailure](https://cloud.githubusercontent.com/assets/4053589/5676390/eedf03fe-9789-11e4-80bd-a5b0dcfea39e.png)

hrev48620

**Comment by waddlesplash** [comment]
This is a bug in HaikuDepot, not BePDF.
