### ISSUE TITLE
Error message: ..."Failed to get gcc version."

### ISSUE THREAD

**Issue by jfjhh** [HaikuArchives/BePDF#20]
During normal use of `BePDF`, the following error message pops up (the error window had the `stdout` as well as the default `stderr` box checked).

![badgcc](https://cloud.githubusercontent.com/assets/4053589/5676410/512f1684-978a-11e4-8676-4a94e8d8f5ee.png)

hrev48620

**Comment by waddlesplash** [comment]
Those are harmless warnings, there's no real way to fix them AFAIK.
