### ISSUE TITLE
There are errors and inconsistencies in the title of the open file

### ISSUE THREAD

**Issue by jfjhh** [HaikuArchives/BePDF#21]
There are errors and inconsistencies in the title of the open file in `BePDF`. Upon opening `alice.pdf`, in `~/Desktop/DemoPackages/.../alice.pdf`, the file is believed to come from `C:\ACTIVE\ADD\11B` (nonexistent). Subsequent files show either the PDF filename, title, or an incorrect path (E.g. `C:\BAD\PATH`).

http://haiku-files.org/files/optional-packages/DemoPackage_Data-0.1-2012-02-19.zip

![falsefilename](https://cloud.githubusercontent.com/assets/4053589/5676447/c1dbb18a-978a-11e4-8bee-0592294e221b.png)
![truefilename](https://cloud.githubusercontent.com/assets/4053589/5676448/c75ea87e-978a-11e4-8a1d-826fcbd85c47.png)

hrev48620

**Comment by waddlesplash** [comment]
Try opening those PDFs in another viewer on a different OS. I think that the `C: ...` stuff is the actual title of the PDF, in which case BePDF is doing what it's supposed to.

**Comment by jfjhh** [comment]
It seems that when opening in Preview, the title is the same as the filename.
![screen shot 2015-01-09 at 10 36 42 am](https://cloud.githubusercontent.com/assets/4053589/5685048/8f99def2-97eb-11e4-9f4f-457615c97a24.png)
However, the title of the pdf is actually a `C: ...` path.
![screen shot 2015-01-09 at 10 40 45 am](https://cloud.githubusercontent.com/assets/4053589/5685109/02de21b6-97ec-11e4-9d86-377037cdc8bc.png)
This occurs with documents created by `Docudesk`, for future reference, but `BePDF` is correct.
