### ISSUE TITLE
Seeking in a PDF causes the page input box to be misplaced, and the text cut off.

### ISSUE THREAD

**Issue by jfjhh** [HaikuArchives/BePDF#22]
Seeking to (atleast) a three-digit page in a PDF causes the page input box to be misplaced, and the text cut off. During entry of text, display is normal, but after seeking, the number is cut off at the second digit. This error remains for smaller pages, and is persistent across invocations of `BePDF`.

![errtextpage](https://cloud.githubusercontent.com/assets/4053589/5676465/12af152a-978b-11e4-8edf-e4dc07e0ed12.png)

hrev48620

**Comment by diversys** [comment]
Seems to be fixed now
