### ISSUE TITLE
Gcc version error window when clicking image in PDF

### ISSUE THREAD

**Issue by jfjhh** [HaikuArchives/BePDF#24]
Related to [bug found previously](https://github.com/HaikuArchives/BePDF/issues/20). When clicking the PDF, the image (which has horrible quality: maybe related to the error) in `haikuwiki.pdf` causes `WebPositive` to open, and also the error window that complains about the version of `gcc` not being found. The bug occurs only when the image is clicked.

http://haiku-files.org/files/optional-packages/DemoPackage_Data-0.1-2012-02-19.zip

![haikuwiki](https://cloud.githubusercontent.com/assets/4053589/5676504/b6ea316a-978b-11e4-9b43-3eb446994a2b.png)

hrev48620

**Comment by waddlesplash** [comment]
The window shouldn't open, but the errors are harmless.

**Comment by waddlesplash** [comment]
Looks like it's fixed.
