### ISSUE TITLE
Switch Xpdf to MuPDF

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BePDF#29]

**Comment by waddlesplash** [comment]
Or Poppler. I'm not sure which is better, really.

**Comment by waddlesplash** [comment]
Eh, XPDF recently released a new version, and it seems to be working pretty well in my offline tests. Needs some adaptations before it's really ready, though.

**Comment by waddlesplash** [comment]
Upgraded XPDF in e46b0389c30d5c16abef02fbe9a7510924e7d04f and subsequent commits; so closing this as WONTFIX.

**Comment by diversys** [comment]
This issue is listed as GCI task. Maybe it would be a cool idea to have MuPDF as an optional backend?

**Comment by waddlesplash** [comment]
No. MuPDF and BePDF are so different that this would constitute a complete rewrite, essentially.
