### ISSUE TITLE
Crash when closing preferences window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/BePDF#33]
Closing the preferences window of BePDF results in the attached crash.   
Culprit is the [CountItems() in MakeEmpty()](https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/LayoutUtils.cpp#L40) that is called from [ClearView()](https://github.com/HaikuArchives/BePDF/blob/master/bepdf/beos/PreferencesWindow.cpp#L365) of the prefs window.
Maybe there's no valid mList?

[BePDF-2248-debug-15-01-2016-15-57-18.report.txt](https://github.com/HaikuArchives/BePDF/files/92155/BePDF-2248-debug-15-01-2016-15-57-18.report.txt)

**Comment by waddlesplash** [comment]
Fixed in 3b84ba3608b303d83134f50ee3c84af9ed4dfc6a.
