### ISSUE TITLE
Missing annotation icons

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/BePDF#40]
The following annotation vector icons don't exist (yet):
```
ANNOT_LINK
ANNOT_LINE
ANNOT_STAMP
ANNOT_INK
ANNOT_POPUP
ANNOT_FILEATTACHMENT
ANNOT_SOUND
ANNOT_MOVIE
ANNOT_WIDGET
ANNOT_PRINTERMARK
ANNOT_TRAPNET
```
cc @humdingerb, in case he wants to try and tackle those

**Comment by humdingerb** [comment]
Do you have the current bitmap icons for those?  I don't think I see those icons when looking at BePDFs GUI.

**Comment by waddlesplash** [comment]
No, it appears I deleted them in the master branch. Run `git reset --hard f8491e5ddd606e4d620f48409b298f4d08e9622d` to go back to before I started using the vector icons.

**Comment by waddlesplash** [comment]
Ah. It appears these aren't used anyway.
