### ISSUE TITLE
Fullscreen button breaks toolbar

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BePDF#46]
Reproducible with annotation toolbar enabled

**Comment by waddlesplash** [comment]
Changing into fullscreen changes nothing but window flags & size, so this must be a bug in Haiku...

**Comment by diversys** [comment]
I think it actually worked recently. Probably before main window was rewritten to use layout

**Comment by diversys** [comment]
Probably fixed in c2d788b.
