### ISSUE TITLE
Merge docs branch into master

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/BePDF#68]
The "docs" branch should probably be merged into the master branch.

We have the problem, that building the PDF versions of the user docs needs ghostscript, which isn't available for Haiku at this time. So currently we'd only have the HTML version. While it may be nice for a PDF viewer to have the doc as PDF, I think going HTML-only is OK.

I also find the separation of headers, footers and templates, and having a complicated script to build it all, is overkill. How about (in the future) we just do static HTML? We can keep the "docs" branch around if we ever want to go back the convoluted way...

**Comment by waddlesplash** [comment]
I still don't know what to do about that, and I haven't had time to poke at it. Since we only rebuild docs now and again, I think we can ignore the problem for now, but yes, we do need to find a more permanent solution...

**Comment by humdingerb** [comment]
How about importing the "docs-build" directory that's build from the "docs-branch" for the time being for now? Then 2.0 can finally be released. :)
I can create a PR for that...

**Comment by diversys** [comment]
Fixed?

**Comment by waddlesplash** [comment]
Indeed.
