### ISSUE TITLE
Switch to Poppler backend

### ISSUE THREAD

**Issue by extrowerk** [HaikuArchives/BePDF#72]
Excerpt from the Poppler README:

> Poppler is a fork of the xpdf PDF viewer developed by Derek Noonburg
> of Glyph and Cog, LLC.  The purpose of forking xpdf is twofold.
> First, we want to provide PDF rendering functionality as a shared
> library, to centralize the maintenance effort.  Today a number of
> applications incorporate the xpdf code base, and whenever a security
> issue is discovered, all these applications exchange patches and put
> out new releases.  In turn, all distributions must package and release
> new version of these xpdf based viewers.  It's safe to say that
> there's a lot of duplicated effort with the current situation.  Even if
> poppler in the short term introduces yet another xpdf derived code
> base to the world, we hope that over time these applications will
> adopt poppler.  After all, we only need one application to use poppler
> to break even.
> 
> Second, we would like to move libpoppler forward in a number of areas
> that don't fit within the goals of xpdf.  By design, xpdf depends on
> very few libraries and runs a wide range of X based platforms.  This
> is a strong feature and reasonable design goal.  However, with poppler
> we would like to replace parts of xpdf that are now available as
> standard components of modern Unix desktop environments.  One such
> example is fontconfig, which solves the problem of matching and
> locating fonts on the system, in a standardized and well understood
> way.  Another example is cairo, which provides high quality 2D
> rendering.  See the file TODO for a list of planned changes.

There is already a work-in-progress recipe for Poppler in HaikuPorts.

**Comment by richienyhus** [comment]
The cairo requirement is a bit of a turn off to be honest.

**Comment by miqlas** [comment]
Cairo just an optional req. AFAIK. I just enabled all the optional features in the haikuporter recipe.

-- Z.

2017.01.09. dátummal, 20:01 időpontban Richard Nyhus <notifications@github.com> írta:

**Comment by waddlesplash** [comment]
XPDF 4.0 fixed a lot of misc. issues, I think we can stick with it for now.

**Comment by extrowerk** [comment]
@waddlesplash : but BePDF needs to be adjusted/rebuilt with xpdf4, right?

**Comment by waddlesplash** [comment]
@extrowerk I just did that, released it, and updated the recipe. :)

**Comment by extrowerk** [comment]
Great!

**Comment by waddlesplash** [comment]
@extrowerk Nope, there are some significant BePDF-specific patches here, and XPDF has no mechanism for generating a shared library anyway.

**Comment by extrowerk** [comment]
@waddlesplash : can't we try to upstream the BePDF specific changes? There is already some platform-specific things in the xpdf tree.

**Comment by waddlesplash** [comment]
@extrowerk Some of them are technically hacks and there's no good way to make them non-hacks, and merges are not much effort, so we can just leave as-is.
