### ISSUE TITLE
Typo in BePDF,translation page

### ISSUE THREAD

**Issue by Naba7** [HaikuArchives/BePDF#85]
In https://i18n.kacperkasper.pl/files/8/lang/26?page=5 ``Add fileattachment annotation`` there is no space between file and attachment.

**Comment by humdingerb** [comment]
You wanna create a pull-request for that?
(BTW, this fix isn't that urgent, as that string/feature isn't implemented or visible in the GUI at the moment)

**Comment by Naba7** [comment]
Yes,I want to open a PR for that. I am translating BePDF to hindi.Will i edit hi.catkeys or just the normal yellow boxes

**Comment by Naba7** [comment]
I have uploaded ``hi.catkeys`` for ``Hindi`` version of ``BePDF``.Kindly check it.Thanks in advance

**Comment by humdingerb** [comment]
The typo was fixed with d45848fe11b6b6cf557948813e35432c7fc8da74.
The Hindi translation is only missing very few strings before it can be added (it's at 93%). Wanna take a look at https://i18n.kacperkasper.pl/projects/7 ?
