### ISSUE TITLE
Translation: Rephrase "translated by" in About BePDF?

### ISSUE THREAD

**Issue by deejam** [HaikuArchives/BePDF#89]
Would changing the translated by string to something more generic be a good idea? Currently, BePDF want to know the translators, which can be tricky to track.

Current string: "Language 'English', translated by the BePDF authors."

With comment for translators: "Replace 'English' with the language you're translating to, and 'the BePDF authors' with your name or your translation group's name."

Maybe smethingmore generic like "Language 'English', translated by the English Haiku translation team."?

**Comment by humdingerb** [comment]
> Maybe smethingmore generic like "Language 'English', translated by the English Haiku translation team."?

I'd say the informing content of such a sentence tends to zero. :)
Polyglot is tracking all Translators of a language, so it's o problem to list all individuals.

**Comment by deejam** [comment]
> Polyglot is tracking all Translators of a language, so it's o problem to list all individuals.
Tracking them (their username, not realname) is no problem. Keeping the information up do date is the problem.

How will you keep track of if a new translator should be added? Currently no routine for that exists and must be created – or just omit the information as suggested in this ticket.

**Comment by humdingerb** [comment]
When exporting the catfiles from Polyglot, I compare translator names.

**Comment by deejam** [comment]
> When exporting the catfiles from Polyglot, I compare translator names.

Do you update the "Language 'English', translated by the BePDF authors." for each language with the up-to-date list of translators?

**Comment by humdingerb** [comment]
I note new/updated translations and their translators when committing the catkeys. In future, I guess I'll have to check if they are also listed in that string.
I don't see a huge problem here. If I forget or mess up, the translators that care about it can notify me (or adjust the string themselves).
